#!/bin/bash
# Larger example, score

trap "/usr/bin/killall -q -u $USER ./Blotto 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./Blotto ]; then
  echo './Blotto is missing or not executable'
  echo './Blotto is missing or not executable' 1>&2
  exit 1
fi


/c/cs474/bin/run -stderr=/dev/null ./Blotto /c/cs223/hw4/Tests/round_robin_25_5.in score 1 2 3 4 5 < /c/cs223/hw4/Tests/t039.in
