#!/bin/bash
# pointset_for_each empty set

trap "/usr/bin/killall -q -u $USER ./PointsetUnit 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./PointsetUnit ]; then
  echo './PointsetUnit is missing or not executable'
  echo './PointsetUnit is missing or not executable' 1>&2
  exit 1
fi


/c/cs474/bin/run -stdout=stdout.out -stderr=/dev/null ./PointsetUnit 6 < /dev/null
cat stdout.out  | /usr/bin/sort -n
