#!/bin/bash
# pointset_add and pointset_destroy do not overflow stack

trap "/usr/bin/killall -q -u $USER ./PointsetUnit 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./PointsetUnit ]; then
  echo './PointsetUnit is missing or not executable'
  echo './PointsetUnit is missing or not executable' 1>&2
  exit 1
fi


ulimit -S -s 40
/c/cs474/bin/run -stderr=/dev/null ./PointsetUnit 22 < /dev/null
