#!/bin/bash
# Large graph, large number of queries, distance

trap "/usr/bin/killall -q -u $USER ./Friends 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./Friends ]; then
  echo './Friends is missing or not executable'
  echo './Friends is missing or not executable' 1>&2
  exit 1
fi


/c/cs474/bin/run -stderr=/dev/null ./Friends /c/cs223/hw6/Tests/graph_numeric_10000.in distance < /c/cs223/hw6/Tests/t037.in
